name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master]

jobs:
  test:
    name: PHP ${{ matrix.php-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        php-version: ['8.4']
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite
          coverage: none
          
      - name: Validate composer.json and composer.lock
        run: composer validate --strict
        
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-version }}-
            
      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress
        
      - name: Run Pint on Example directory
        run: ./vendor/bin/pint --config=pint.json --test Example/
        
      - name: Run PHPCS on main files (check only)
        run: ./vendor/bin/phpcs Example/ --standard=vendor/pekral/phpcs-rules/ruleset.xml
        
      - name: Check for security vulnerabilities
        run: composer audit --format=json --audit-format=json || true
        
      - name: Upload Pint results as artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: pint-results-${{ matrix.os }}-${{ matrix.php-version }}
          path: |
            .pint.cache
            Example/
          retention-days: 7
          
      - name: Upload PHPCS results as artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: phpcs-results-${{ matrix.os }}-${{ matrix.php-version }}
          path: |
            Example/
          retention-days: 7 